### ISSUE TITLE
widgets titles & subtitles

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway#2301]
Today, the titles for the various widgets arrive from a different parts of the JSON. 
Parts of the title comes from the JSON **meta** and some in the widget **text**. 
That causes lack of clarity and inconsistently for the FrontEnd team.
In addition, there is a issues of repetitiveness in texts.
We would also like to improve and prepare the file structure for future changes. 

**The requerd change**
![image](https://user-images.githubusercontent.com/61007501/206259767-7ed38ba1-c43a-4e45-98fe-d2315736c9f1.png)

"title": no change
"subtitle":  contain the location: road segment name or street name
for exsample במקטע צומת נהלל -צומת השומרים או ברחוב לבנון צבי ירושלים   

**here are few specific changes:**
widget name: accident_count_by_accident_year
text: מספר תאונות לפי חומרה

widget name: injured_count_by_accident_year
text: מספר נפגעים לפי חומרה

widget name: accident_count_by_day_night
text:מספר  תאונות לפי תקופה ביום 

widget name: top_road_segments_accidents_per_km
information: שלושת המקטעים עם הכי הרבה תאונות לקילומטר, בכביש בינעירוני

widget name: accidents_heat_map 
information: צפיפות תאונות במקטע. כחול =צפיפות גבוהה ורוד=צפיפות נמוכה

widget name: vision_zero_2_plus_1
information: פתרון נתיבים מתחלפים, 2 + 1 למניעת תאונות קטלניות בכביש בינעירוני

widget name: accident_severity_by_cross_location
information: מספר הולכי רגל שנפגעו קשה או נהרגו ברחוב לפי מיקום החצייה
"title":  מספר תאונות במעורבות הולכי רגל לפי מיקום החציה ברחוב
We want to split the issue to three different PRs:
1 - The JSON structure change, i.e. in widgets where there is only `title`, remove the location part from it, and add the field `subtitle` with the location (that was removed from `title`), as shown in the image above.
2 - The first half of title changes
3 - The rest of the title changes.

**Comment by MichalOren** [comment]
@atalyaalon  kindly check if ok and assing

**Comment by ziv17** [comment]
Hi,
1 - if field `subtitle` always contains location, do we want to rename it to `location`?
2 - Regarding
widget name: accident_count_by_accident_year
text: מספר תאונות לפי חומרה
  By referring to field `text`, you actually mean `text -> title`?
3 - It is a simple change in each widget, but if we want to give it to a new volunteer, I would break it to several issues, and name specific widgets for each issue. It will also make the coordination with FE easier.

**Comment by MichalOren** [comment]
Hi ziv
1. A broader definition like tiitle/subtitle would be appropriate because it is not clear what will happen next
2.  yes you ar correct
3.  i can split it to 2 part

**Comment by ziv17** [comment]
Hi @MichalOren 
1. I accept.
2. OK,
3. Yes, a good idea. First just a change of the JSON format, afterwards a change in the text value.

**Comment by ziv17** [comment]
Hi @atalyaalon , @danielsh28,
It seems to me that this a breaking change (i.e. needs a change also in FE).
Do we want to do it in one go, or maybe have the FE accept both old and new, and then do the change in BE gradually?
What do you think?

**Comment by adirbru** [comment]
@ziv17 @atalyaalon 
I checked the code to commit changes related to `The JSON structure change`, but from what I see in the code - I'm not sure changes are needed in this case.

The json is added to the response in `anyway/infographics_utils.py`'s `localize_after_cache` function:
                `res.append(widget_class.localize_items(request_params, items))`

And each item is setting its own json keys in its implementation of `localize_after_cache`.
So the FE will see these changes only once I'll implement the subtitle for each widget. 
Or did I misunderstand the first PR you were referring to?

For example, In the following widgets, these jsons responses were returned from the API once I split the title to title and subtitle (without further changes in the backend):
```
widget_name: top_road_segments_accidents_per_km
title: מקטעים עם הכי הרבה תאונות לק"מ
subtitle: 531

widget_name: accident_count_by_road_light
title: מספר תאונות לפי תאורה
subtitle: מחלף שמריהו מזרח - מחלף אלישמע

widget_name: accidents_heat_map
title: מוקדי תאונות קטלניות וקשות במקטע
subtitle: מחלף שמריהו מזרח - מחלף אלישמע

widget_name: killed_and_injured_count_per_age_group
title: נפגעים לפי קבוצת גיל
subtitle: במקטע מחלף שמריהו מזרח - מחלף אלישמע

widget_name: injured_count_by_accident_year
title: מספר נפגעים לפי שנה, לפי חומרה
subtitle: מחלף שמריהו מזרח - מחלף אלישמע

widget_name: injured_count_by_severity
title: מספר תאונות לפי חומרה
subtitle: מחלף שמריהו מזרח - מחלף אלישמע

widget_name: killed_and_injured_count_per_age_group_stacked
title: חומרת פגיעה לפי קבוצת גיל
subtitle: במקטע מחלף שמריהו מזרח - מחלף אלישמע

widget_name: accident_count_by_severity
title: מספר תאונות לפי חומרה
subtitle: מחלף שמריהו מזרח - מחלף אלישמע

widget_name: seriously_injured_killed_in_bicycles_scooter
title: Number of severely injured or killed in bike, e-bike, or scooter accidents
subtitle: כביש 531 במקטע מחלף שמריהו מזרח - מחלף אלישמע
```

**Comment by ziv17** [comment]
Hi @adirbru ,
I did not explain myself well. I updated the description. I mean that in widgets that in widgets where there is only `title`, remove the location part from it, and add the field `subtitle` with the location (that was removed from `title`)

**Comment by adirbru** [comment]
@ziv17 Cool, this is basically what I did, but I'm not sure I understand the 3 PRs split in that case.
I committed what you said in this comment (moving the location part from the widgets with `title` only to a `subtitle`), so maybe by looking at the code you could tell me if I got this right or not.
Couldn't figure out how to set you as a reviewer though, so here's the [link to the PR](https://github.com/data-for-change/anyway/pull/2314)
