### ISSUE TITLE
[Bug] fix black tests

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2332]
**Describe the bug**
Black tests are not passing
@ziv17 FYI, @BarVolunteering will take this one

**Comment by ziv17** [comment]
Just FYI, it seems that currently the bin/black.sh runs black on a small subset of our `.py` sources.

**Comment by BarVolunteering** [comment]
@atalyaalon Is this done by someone else?

**Comment by atalyaalon** [comment]
done
