### ISSUE TITLE
Change from SubUrbanWidget to AllLocationsWidget and fix code (killed_and_injured_count_per_age_group, injured_count_by_severity)

### ISSUE THREAD

**Issue by BarVolunteering** [data-for-change/anyway#2373]
Need to change from SubUrbanWidget to AllLocationsWidget + change the code of the widget it self:
killed_and_injured_count_per_age_group
injured_count_by_severity

and test each with street2_hebrew.

Epic: #2333

**Comment by BarVolunteering** [comment]
Not relevant

**Comment by atalyaalon** [comment]
@MichalOren what do you think?

**Comment by BarVolunteering** [comment]
@atalyaalon Mistake, good catch

**Comment by atalyaalon** [comment]
initial pr: https://github.com/data-for-change/anyway/commit/caebb0c961cf0f7a0c1d604b93aeaa59b8a5a385

**Comment by atalyaalon** [comment]
Great work @EliorGigi !
