### ISSUE TITLE
changing newsflash's location throguh UI throws error about permissions

### ISSUE THREAD

**Issue by tkalir** [data-for-change/anyway#2460]
changing newsflash's location throguh UI throws error about permissions even when logged with admin

**Comment by atalyaalon** [comment]
We're having a challenge to debug this issue with current environment. @Shai2022 will try to assist us with better setup of our environment (after the awesome work of adding the FE repo to our docker-compose). This feature on hold for now until this is sorted

**Comment by tkalir** [comment]
admin users did not have permission for this endpoint, also created a user role for this endpoint specifically.
