### ISSUE TITLE
Widget: re-orgenize subtitle with road section or street

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway#2479]
**Re orgenize title & subtitle**
The simple rule is that the title contains the subject of the widget and the subtitle describe the location (road section or street)
Currently there is a mix of content that reaches the title & subtitle. 
For exsample, in widgets: 
accident_count_by_severity & injured_count_by_severity the word במקטע inserted by FE team
in widgets 
most_severe_accidents & most_severe_accidents_table the word במקטע inserted by BE team
In addition, our general policy is that titles are implemented in JSON by the BE team and displayed by FE team.

**Required fix**
The word במקטע או רחוב need to be updated in JSON by BE team for all existing wigest in subtitle 

**Proposed Visualization**
![image](https://github.com/data-for-change/anyway/assets/61007501/a0e21882-92b8-444f-932b-95fcff58ecf8)

**Comment by atalyaalon** [comment]
@tkalir I assigned this to you, not urgent, continue with your current issues for now, we'll decide together on priorities

**Comment by atalyaalon** [comment]
@MichalOren is this done?
