### ISSUE TITLE
Infographic Widgets - Support widget selection also according to current request params

### ISSUE THREAD

**Issue by ziv17** [data-for-change/anyway#2573]
Currently the decision whether a widget is included takes place after its items are generated, before insertion to cache. Cache is based only on location

We want to add the ability to select widgets also according to current request parameters that are not location, e.g. news-flash text.

**Comment by ziv17** [comment]
Implementation suggestion:

- Widgets that need to be included according to current data, will set their `is_included()` to return `True` whenever their data is not empty.
- We will add a method `is_included_after_cache()`, that will receive the current request parameters, and the data that was retrieved from cache. In this method the logic of whether the widget should be included will take place, according to both the items, and the current request parameters.

@atalyaalon , is this along the lines you intended?

**Comment by atalyaalon** [comment]
> Implementation suggestion:
> 
> * Widgets that need to be included according to current data, will set their `is_included()` to return `True` whenever their data is not empty.
> * We will use Shani's method `update_result()`, that receives the current request parameters, and the data that was retrieved from cache. In this method the logic of whether the widget should be included will take place, according to both the items, and the current request parameters.
> 
> @atalyaalon , is this along the lines you intended?

Yes, I assume that in some cases we would like to have an "AND" between data logic and request parameters logic (for example, X pedestrians were injured in street AND "הולך רגל" is in news flash text) and in some cases we would like to have an "OR between them (for example, X pedestrians were injured in street OR "הולך רגל" is in news flash text)

If we have an "OR" the result of each trigger will be the same - the appearance of the widget in the cache data.

**Comment by ziv17** [comment]
> > Implementation suggestion:
> > 
> > * Widgets that need to be included according to current data, will set their `is_included()` to return `True` whenever their data is not empty.
> > * We will use Shani's method `update_result()`, that receives the current request parameters, and the data that was retrieved from cache. In this method the logic of whether the widget should be included will take place, according to both the items, and the current request parameters.
> > 
> > @atalyaalon , is this along the lines you intended?
> 
> Yes, I assume that in some cases we would like to have an "AND" between data logic and request parameters logic (for example, X pedestrians were injured in street AND "הולך רגל" is in news flash text) and in some cases we would like to have an "OR between them (for example, X pedestrians were injured in street OR "הולך רגל" is in news flash text)
> 
> If we have an "OR" the result of each trigger will be the same - the appearance of the widget in the cache data.

It is supported by the current structure. The `update_result()` of the widget can implement the needed logic of that widget. It can alter the widget's data, and it can return None, to remove the widget from the result of the current request.
