### ISSUE TITLE
Filter Location Accuracy in Widgets queries

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2604]
In Urban Widgets queries: only location_accuracy = 1 (עיגון מדויק) OR location_accuracy = 3 (מרכז דרך)
In Sub-Urban queries: only location_accuracy = 1 (עיגון מדויק) OR location_accuracy = 4 (מרכז קילומטר)

Perhaps these queries should be a part of our "queries infrastructure", just like filtering a sub-urban segment query (with junctions as well) is a part of the infrastructure.

**Comment by ziv17** [comment]
Hi @atalyaalon , will this be also correct for urban and sub-urban junctions when we will add them?

**Comment by ziv17** [comment]
Hi @atalyaalon , actually, this should go by the resolution, rather then by the widget, right? The only difference is with `all_location_widget`.

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , will this be also correct for urban and sub-urban junctions when we will add them?

yes

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , actually, this should go by the resolution, rather then by the widget, right? The only difference is with `all_location_widget`.

@ziv17 yes, but of course it affects the widget's data. But yes by the resolution we can set the location accuracy filters when calculating the cache.
