### ISSUE TITLE
[Bug] map infographics are sometimes blurred on telegram

### ISSUE THREAD

**Issue by tkalir** [data-for-change/anyway#2638]
map infographics are sometimes blurred on telegram, probably caused by the image being downloaded before the page finished to fully load (the infographics to image file process is based on screenshot-ing). 
We should try to increase the sleep time on this function generate_infographics_in_selenium_container before it starts downloading.

https://github.com/data-for-change/anyway/blob/b6e5760d58ac06d1daed2f83a14d195ff3d55181/anyway/infographic_image_generator.py#L86

![image](https://github.com/data-for-change/anyway/assets/24721996/9870f808-fd69-4c08-904a-accb03ec0463)

**Comment by atalyaalon** [comment]
@tkalir is this still relevant?

**Comment by tkalir** [comment]
I see we increased the wait for the page to load, and recent images seem fine, so I think it's solved.
