### ISSUE TITLE
[Bug] Accident record yishuvs appear with yishuv_name "לא רשום"

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2687]
**Describe the bug**
There are accident records with yishuv_name "לא רשום" and road_segment_name that exists.
Also - we need to check if there are urban accidents with yishuv_name "לא רשום"
I believe the reason for that is the new "cities" script that contains this record - [see here](https://data.gov.il/api/3/action/datastore_search?resource_id=8f714b6f-c35c-4b40-a0e7-547b675eee0e&limit=100000).

**To Reproduce**
[redash query](https://redash.dataforchange.org.il/queries/79/source)

**Expected behavior**
1. We don't want to have any yishuv_name "לא רשום" record. If there is no yishuv, the yishuv_name should be empty.
2. We want to remove such records from news_flash table that were effected by this bug (I think we'll just rerun in production location script that fills the news_flash table).

**Comment by ziv17** [comment]
Hi @atalyaalon ,
What do you think is the better solution:

1. Remove the line with `yishuv_symbol=0` from `cbs_cities` table?
2. Change the line  with `yishuv_symbol=0` in `cbs_cities` to have `yishuv_name=NULL`, or `yishuv_name=""`?
3. Change the code that loads accidents to place `NULL` in `yishuv_symbol` and `yishuv_name` in these situations?

**Comment by atalyaalon** [comment]
Good question. I think that we need to make sure yishuv_name is NULL in the DB.
I think we should keep `yishuv_symbol=0` since data in the accidents table is mostly raw. However, we do need to make sure the above, I think it can be in the `cbs_cities` table, making sure that re-loading the table preserves `yishuv_name=NULL` in these cases.
