### ISSUE TITLE
News Flash API

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2697]
currently no pagination in News Flash API
[(See this issue in FE)](https://github.com/data-for-change/anyway-newsflash-infographics/issues/1051)

Hence we want to modify News Flash API [as described here](https://github.com/data-for-change/anyway-newsflash-infographics/issues/1051#issuecomment-1973157249), without changing current functionality.
If current functionality is changed, please coordinate with SejoB ( FE  tem) for adjustments needed in FE of current API.

**Comment by atalyaalon** [comment]
@ziv17 this is currently top priority.

**Comment by atalyaalon** [comment]
Also. Previous BE volunteer working on this and talked to SejoB (Sergey) wrote the following:
![Screenshot 2024-09-07 at 19 53 17](https://github.com/user-attachments/assets/3a197712-6981-488e-8f4f-aab5d7d7eb17)

**Comment by atalyaalon** [comment]
relevant pr that removes unused API: https://github.com/data-for-change/anyway/pull/2644/files

**Comment by ziv17** [comment]
Hi @atalyaalon ,
The PR that I prapare should build upon PR #2644? (or it will be merged before that PR?)
Which news-flash APIs, or URLs are included in the issue?

**Comment by atalyaalon** [comment]
@ziv17 I'm working on merging it today, so you'll build upon it (After merge)
This issue is on API urls in `/api/news-flash`
Note that exist a specific url of specific id: `/api/news-flash/<int:news_flash_id>` 
As mentioned we want to change this api and make sure we're adding the offset.

**Comment by atalyaalon** [comment]
@ziv17 merged :) you can use dev branch

**Comment by ziv17** [comment]
Hi @atalyaalon ,
Do we want to keep both `offset` and `pageNumer` (and `limit` with `pageSize`)? 
If not, to deprecate `offset` and `limit`?

**Comment by atalyaalon** [comment]
@ziv17 I suggest coordinating this decision with Sergey.
We can deprecate some, but make sure we're either backward compatible OR that we modify FE and BE at the same time.
