### ISSUE TITLE
Infographics cache for street - reduce run time

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2699]
Between 10.8.24 and 17.8.24 we merged prs to master (I believe it's [this one](https://github.com/data-for-change/anyway/pull/2672/files)) that increased streets cache loading by a significant amount.

(See loading times for the last task [here](https://airflow.anyway.co.il/dags/import-email-to-s3-and-update-data/grid)- fill-infographics-cache-for-streets)

Debug this issue to reduce to previous run time (or less)

**Comment by atalyaalon** [comment]
@ziv17 this is your next issue :) let me know if you need anything

**Comment by ziv17** [comment]
Hi @atalyaalon ,
I forgot to add index to street1/2 to `involved_markers_hebrew`. I think this is one of the major reasons.
I found a couple of additional small items to change to reduce time. I will prepare a PR.

**Comment by atalyaalon** [comment]
@ziv17 great, thanks for the update!
