### ISSUE TITLE
[Bug] Internal Server Error from data-infographics API

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2736]
**Describe the bug**
when querying [this news flash](https://anyway-infographics-staging.web.app/newsflash/231352) - news flash id=231352

When looking at [newsflash API ](https://www.anyway.co.il/api/news-flash/231352) street1_hebrew has \t in it.
I think that's that's one problem we need to fix, perhaps with strip func before adding yishuvs/streets to DB (but not all of it, I think there is another problem):
In addition, when using the search API for this street, we get the same Internal Server Error. Does this mean that this street has no data? https://anyway-infographics-staging.web.app/cityAndStreet/%D7%A2%D7%A8%D7%A2%D7%A8%D7%94/%D7%90%D7%9C%20%D7%93%D7%94%D7%A8%D7%90%D7%AA

**To Reproduce**
API: https://www.anyway.co.il/api/infographics-data?lang=he&news_flash_id=231352&years_ago=5

**Expected behavior**
Return widgets if there are any for the newsflash location, and no widgets (empty dict as json) if there aren't any for the newsflash location

**Screenshots**
<img width="657" alt="Screenshot 2024-12-18 at 12 58 17" src="https://github.com/user-attachments/assets/facb68e5-10f0-4f56-82c6-41204282d306" />

**Environment**
System: Mac

**Additional context**

**Comment by atalyaalon** [comment]
@ziv17 can you take a look?

**Comment by ziv17** [comment]
Hi @atalyaalon ,
What should be returned if a newsflash with the given ID is not found?

**Comment by ziv17** [comment]
Hi @atalyaalon ,
Look at `anyway/flask_app.py:1290`. There is code there that specifically returns error if the returned widget list is empty. Should it be removed?

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , What should be returned if a `news_flash_id` parameter is provided, and a newsflash with the provided ID is not found?

I don't think this is the case - since the current news flash id 231352  exists in production

However, if it's not found I guess we should return some kind of error, perhaps 404?

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , Look at `anyway/flask_app.py:1290`. There is code there that specifically returns error if the returned widget list is empty. Should it be removed?

I think we need differ between 2 cases:
1.  Location exists but no accidents are in our DB
2. Location does not exist

For the first case, which, I believe is our current case, I suggest that for now, sending an empty list is fine, and we might want to send in the future a special widget indicating that no accidents in DB for this location.

For the second case - I think that [sending this error is OK](https://github.com/data-for-change/anyway/blob/6d334ca9cbb6037959ba89d5251ac1e8bad4e6af/anyway/flask_app.py#L1290)

Is it easy to differ these two cases?

**Comment by ziv17** [comment]
Hi @atalyaalon ,
> I think we need differ between 2 cases:
> 
>     1. Location exists but no accidents are in our DB
> 
>     2. Location does not exist
> 
Should we differ between location does not exist and given `newsflash` id does not exist? If yes, in what way? because currently our error message is "The requested URL was not found".

**Comment by ziv17** [comment]
Hi @atalyaalon ,
> I think we need differ between 2 cases:
> 
>     1. Location exists but no accidents are in our DB
> 
>     2. Location does not exist
> 
Should we differ between location does not exist and given `newsflash` id does not exist?

**Comment by atalyaalon** [comment]
> Hi @atalyaalon ,
> 
> > I think we need differ between 2 cases:
> > ```
> > 1. Location exists but no accidents are in our DB
> > 
> > 2. Location does not exist
> > ```
> 
> Should we differ between location does not exist and given `newsflash` id does not exist?

I guess it would be a best practice, either to differ or to have a debug log for that

**Comment by ziv17** [comment]
Hi @atalyaalon ,
This newsflash location has issues:

1. It does not have numeric values for the location fields
2. The street name has a tab `\t` appended to it, and this is not recognized.

**Comment by ziv17** [comment]
To summarize:

1. If newsflash not found, or address not found, we return 404, URL not found.
2. If we find the address, but no accidents, we return empty data.
