### ISSUE TITLE
Add a parser for Shomrei HaDerech data

### ISSUE THREAD

**Issue by r-darwish** [data-for-change/anyway#754]

**Comment by r-darwish** [comment]
I began working on this in the `rsa` branch.

**Comment by r-darwish** [comment]
I managed to get a working parser. We have some difficulties, though:

1. We were asked not to distribute the data file. This means that I can push the code that parses it but we can't have a working example in Heroku, so we'll either have to work with me posting screenshots, or get a permission to commit the data file into our repository.

1. There are no IDs in the data file and our `id` column in the database doesn't seem to support auto increment. What I did for now is to generate id locally in the script, but we need to come up with a better solution. Also, the fact that I have no IDs makes it difficult to know whether a specific row was already imported. 

1. There are no dates in the data file, which poses two difficulties:
   1. The UI always sends `start_time` and `end_time`, which effectively means that we always filter by date. Since the RMS data has no dates, then they will never be displayed in the UI.
   1. The UI itself expects both United and CBS data to have dates. We'll have to refactor it if we expect data without any dates.

**Comment by simonaho** [comment]
About 1 I think we can explain Yair that Herouku is our integration server That is not used formally yairnat@gmail.com I believe he will agree.
About 2 Lets also discuss with Yair, I hope they can provide an id
About 3 lets ask for a date from Yair, if they cannot provide a date, we can use the file creation date
Will you write an email to him?

**Comment by r-darwish** [comment]
I prefer that you contact him

**Comment by simonaho** [comment]
Sent

**Comment by r-darwish** [comment]
Thanks. In the meantime we'll proceed with the artificial ID and I'll add an artificial date.
