### ISSUE TITLE
Add CBS monthly data collection script to crontab

### ISSUE THREAD

**Issue by simonaho** [data-for-change/anyway#808]
Add CBS monthly data collection script to crontab:

- [x] Add CBS data to an S3 bucket - create a repo for provider code and for each year.
- [x] Import cbs data from email and upload to AWS - nowdays importmail process is running once a week and uploads to s3 data from last 2 cbs emails
- [ ] Trigger Load CBS data from s3 when new CBS data arrives
command to delete a certain year and load starting that year, for example 2019:
`python main.py process cbs --path <cbs dir path> --delete_start_date 2019-01-01 -load_start_year=2019`
cbs parser is in file cbs.py
delete only data starting the year of the current files that arrived
- [ ] Create DB table versioning of emails we load from email to s3, and load new data to s3 only when new data arrives
- [ ] Modify schedule from weekly back to daily (see this pr that changed [from daily to weekly](https://github.com/hasadna/anyway-etl/pull/8))

Note that CBS processes are now in anyway-etl repo - see [process repo here](https://github.com/hasadna/anyway-etl)

**Comment by atalyaalon** [comment]
@erezh31 , can you take this issue?
I can guide you regarding the email format.

**Comment by erezh31** [comment]
I think.. we can talk about it next meeting

**Comment by atalyaalon** [comment]
replaced by https://github.com/data-for-change/anyway/issues/2745
